__author__ = "Salvatore Giorgi, Maarten Sap, Phillip Lu, Selah Lynch"
__email__ = "sal.giorgi@gmail.com"
__copyright__ = "Copyright 2017"
__license__ = "Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License: http://creativecommons.org/licenses/by-nc-sa/3.0/"
__version__ = "0.5"
